language: java
jdk:
  - oraclejdk8
before_script: 
  cd sonar-connector
addons:
  sonarcloud:
    organization: "rodrigogrohl-github"
    branches:
      - master
      - develop
script:
- mvn clean install sonar:sonar